### ISSUE TITLE
Ispraviti reporting testova

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#139]
Popraviti sve testove tako da na kraju testa ispisuje je li test uspješan ili nije.

Neki testovi imaju napomenu:

TEST: Test is still not reporting the results correctly. Read https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

(npr. test 38).

Složiti sve testove (koji rade) u skladu s uputama na navedenoj wiki stranici.

Link(https://github.com/AILab-FOI/akdb/issues/13)

**Comment by kmedenjak** [comment]
Javljam se za ovaj issue.
