### ISSUE TITLE
Privileges.c ne radi kod pokretanja testova. Popraviti testove.

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#142]
Privileges.c ne radi kod pokretanja testova. Popraviti testove.

Link(https://github.com/AILab-FOI/akdb/issues/39)

**Comment by minovakovi** [comment]
sql: AK_privileges

`nakon prvog testiranja ne prolazi 14. test, no nakon svakog idućeg testiranja ne prolaze dodatna 3 testa`
Popraviti testove.

**Comment by minovakovi** [comment]
Test 45 privileges ponekad vraća SIGSEGV

Provjeriti (uz debugger) o čemu je riječ i ispraviti pogreške. Nakon otklanjanja SIGSEGV errora analizirati logičku ispravnost implementacije te po potrebi složiti izvještavanje o testu u skladu s uputama na wiki stranici:

https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by minovakovi** [comment]
U prvom testu se događa da AK_check_privilege vraća da korisnik user2 nema pravo na UPDATE tablice student

user2 je prije toga dobio pravo na UPDATE nad tablicom student

U drugom prolasku testa se događa da dodavanje korisnika user1 funkcijom AK_user_add ne prolazi

U ponovnim testiranjima se pojavljuju nove greške

**Comment by minovakovi** [comment]
Dodatne informacije:

Analizom koda datoteke privileges.c možemo vidjeti kako postoji 19 testova, ali u mom slučaju kod pokretanja testa odmah nakon prvog uspješnog testa javlja se SIGSEGV odnosno prilikom testiranja kod je pokušao pristupiti dijelu memorije kojem ne može pristupiti.

Kao što nam i sam program nudi rješenje za poboljšanje nakon izvršenog testiranja, prijedlog za poboljšanje je korištenje AK_free funkcije kako bi se oslobodila memorija sustava.

**Comment by minovakovi** [comment]
Djelomično ispravljeno. Nedostaje rješenje za test 14.

**Comment by BornaRomic** [comment]
Javljam se za rješenje ovog problema.
