### ISSUE TITLE
Ujednačavanje nazivlja 

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#162]
Ponegdje je naziv ak, ponegdje AK, ponegdje Ak. U svim datotekama (c, h, i/swig, py, sh itd.) promijeniti na velika slova AK. Testirati sve dijelove da nije došlo do novih pogrešaka.

Link(https://github.com/AILab-FOI/akdb/issues/178)

**Comment by IvaKozmac** [comment]
Javljam se za ovaj issue.
