### ISSUE TITLE
Ispraviti table.c|h 

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#171]
file/table.c – ispraviti grešku u funkciji “AK_table_test”,
pokušati razdvojiti neke relativno složene funkcije za veću
čitljivost, dokumentirati funkcije bez opisa

file/table.h – ukloniti nepotrebne biblioteke

Obratiti pozornost na https://github.com/AILab-FOI/akdb/issues/173 (npr. komentar br. 17)

Link(https://github.com/AILab-FOI/akdb/issues/220)

**Comment by Barbara0303** [comment]
javljam se za ovaj issue
