### ISSUE TITLE
Ispraviti selection.c test

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#180]
Prijedlog poboljšanja odnosi se na datoteku selection.c, u toj datoteci testiranje WHERE klauzule i operatora BETWEEN i AND ne rade, prilikom izvođenja tog testa dolazi do core dumped (ako se pokrene kao akdb test 31). Testna funkcija je AK_op_selection_test.

Prilikom pokretanja testa 32 (ako se pokrene kao akdb test 31) koji u sebi testira operatore LIKE, ILIKE i SIMILAR TO, dolazi do poruke invalid pointer (core dumped). Testna funkcija koja ne radi je AK_op_selection_test_pattern.

Link(https://github.com/AILab-FOI/akdb/issues/250)

**Comment by thlevnjak** [comment]
javljam se za ovaj issue

**Comment by tjelavic5** [comment]
javljam se za ovaj issue
