### ISSUE TITLE
Implementacija testova za dictionary.c i iniparser.c 

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#184]
Napisati unit testove za dictionary.c i iniparser.c koji ih trenutno nemaju. Testove dodati u main.c. Obratiti pozornost na https://github.com/mschatten/akdb/wiki/Reporting-Test-Results

Link(https://github.com/AILab-FOI/akdb/issues/260)

**Comment by eudbinac** [comment]
Javljam se za ovaj issue
