### ISSUE TITLE
Provjeriti i implementirati test za funkciju create table 

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#186]
U table.c je implementirana funkcija AK_create_table, no nigdje se ne koristi i ne postoji test. Potrebno je testirati funkciju i implementirati test.

Link(https://github.com/AILab-FOI/akdb/issues/280)

**Comment by mmataija** [comment]
javljam se za ovaj issue

**Comment by eudbinac** [comment]
Javljam se za issue
