### ISSUE TITLE
Popraviti html dokumentaciju

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#192]
Popraviti dokumentaciju u html_files/*

Pobrisati višak koda, ukloniti nepotrebne komentare i urediti kod.

Potrebno je popraviti skripte instalacije i ispraviti putanje kod kreiranja dokumentacije doc/

**Comment by ErikBaukovac** [comment]
Javljam se za ovaj issue

**Comment by mbogesic** [comment]
Javljam se

**Comment by Marko2407** [comment]
javljam se za ovaj issue

**Comment by Marko2407** [comment]
Gdje se nalaze instalacijske skripte, projekt je podosta velik pa nisam siguran gdje se nalaze.  @minovakovi
