### ISSUE TITLE
view.c i select.c

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#235]
Refaktorirati 201:AK_view_rename: prvo provjeriti postoji li view s tim imenom, ako ne postoji vratiti grešku,
ako postoji tek onda tražiti njegov query i relation expression i onda napraviti rename. Nepotrebna iteracija po
svim viewovima.

Potencijalno razlamanje funkcije 106:AK_select na manje funkcije.

**Comment by eudbinac** [comment]
javljam se
