### ISSUE TITLE
Test 29

### ISSUE THREAD

**Issue by minovakovi** [minovakovi/akdb#236]
Ispisuju se tablice professor i assistant nakon čega treba provesti operaciju unije. Dolazi do pogreške - free(): double free detected in tcache 2. 
Ukazuje na to da je u kodu negdje oslobođena momorija na koju pokazuje neki pointer,

**Comment by daria-komic** [comment]
Javljam se za ovaj issue

**Comment by AndrejHre123** [comment]
Javljam se za ovaj issue.

**Comment by bujin2502** [comment]
Javljam se
